### ISSUE TITLE
Link to Play Broken

### ISSUE THREAD

**Issue by Aurorum** [Ep8Script/Club_Penguin_Minigames#1]
Hi @Ep8Script! :wave: It seems that the links to play these mini-games which are in the README are broken. Is there an updated link where I could check the games out?

**Comment by Ep8Script** [comment]
Hi! I'm very sorry about that, I forgot to update the link here (while I still sort out getting my domain back). The link to access them for now is https://ep8script.github.io/Club_Penguin_Minigames/ - thank you for your interest!
